default: Driver/DoubleQueueDriver.java com/gradescope/DoubleQueue/code/ArrayDoubleQueue.java com/gradescope/DoubleQueue/code/IDoubleQueue.java com/gradescope/DoubleQueue/code/ListDoubleQueue.java
	javac Driver/DoubleQueueDriver.java com/gradescope/DoubleQueue/code/ArrayDoubleQueue.java com/gradescope/DoubleQueue/code/IDoubleQueue.java com/gradescope/DoubleQueue/code/ListDoubleQueue.java

run: Driver/DoubleQueueDriver.class com/gradescope/DoubleQueue/code/ArrayDoubleQueue.class com/gradescope/DoubleQueue/code/IDoubleQueue.class com/gradescope/DoubleQueue/code/ListDoubleQueue.class
	java Driver.DoubleQueueDriver.class com.gradescope.DoubleQueue.code.ArrayDoubleQueue.class com.gradescope.DoubleQueue.code.IDoubleQueue.class com.gradescope.DoubleQueue.code.ListDoubleQueue.class

clean:
	
